// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxEMrMXuBfJ5ba02TLLW6TMESWKUWkovM',
    appId: '1:722085607014:web:ba1f89a9fcdeca803edfa7',
    messagingSenderId: '722085607014',
    projectId: 'chat-app-2a72f',
    authDomain: 'chat-app-2a72f.firebaseapp.com',
    storageBucket: 'chat-app-2a72f.appspot.com',
    measurementId: 'G-XCMSH8LKFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNJT_q1CS3wsmQ4To6UcAAFFdjs8opPR4',
    appId: '1:722085607014:android:e083720de8807e943edfa7',
    messagingSenderId: '722085607014',
    projectId: 'chat-app-2a72f',
    storageBucket: 'chat-app-2a72f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkhrEn2xnKtQK3hlVugYmoGFHmBWuqyk',
    appId: '1:722085607014:ios:64e02bdd2bb225a33edfa7',
    messagingSenderId: '722085607014',
    projectId: 'chat-app-2a72f',
    storageBucket: 'chat-app-2a72f.appspot.com',
    iosClientId: '722085607014-1bb7hj1hkrafui5d1vdq0d8rach8jkkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACkhrEn2xnKtQK3hlVugYmoGFHmBWuqyk',
    appId: '1:722085607014:ios:64e02bdd2bb225a33edfa7',
    messagingSenderId: '722085607014',
    projectId: 'chat-app-2a72f',
    storageBucket: 'chat-app-2a72f.appspot.com',
    iosClientId: '722085607014-1bb7hj1hkrafui5d1vdq0d8rach8jkkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
